version: "3"
services:
  mongodb:
    image: "mongo"
    ports:
    - "27017:27017"
    container_name: "mongodb"
    volumes:
    - ./data/mongo:/data/db
  hyperopt:
    build:
      context: ./hyperopt
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    environment:
      EXP_KEY: ${EXPERIMENT_KEY}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MAX_EVALS: ${MAX_EVALS}
      HYPEROPT_DIR: ${HYPEROPT_DIR}
    links:
      - mongodb
    container_name: "hyperopt"
    volumes:
      - ./hyperopt/src:/hyperopt/
      - ./hyperopt/data:/hyperopt/data/
      - ./hyperopt/models:/hyperopt/models/
  hyperopt-mongo-worker:
    build:
      context: ./hyperopt
      dockerfile: Dockerfile
    depends_on:
      - hyperopt
      - mongodb
    links:
      - mongodb
    deploy:
      replicas: 4
    environment:
      EXP_KEY: ${EXPERIMENT_KEY}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MAX_EVALS: ${MAX_EVALS}
      HYPEROPT_DIR: ${HYPEROPT_DIR}
    command: ["hyperopt-mongo-worker", "--mongo=mongodb:27017/foo_db", "--poll-interval=0.1"]
    volumes:
      - ./hyperopt-mongo-worker/:/hyperopt/
      - ./hyperopt/data:/hyperopt/data/
      - ./hyperopt/models:/hyperopt/models/